[package]
name = "raw-window-handle-ffi"
version = "0.1.0"
edition = "2024"
authors = ["Redchin Daniil <redchindaniil@gmail.com>"]
repository = ""

[dependencies]
cbindgen = "0.28.0"
raw-window-handle = "0.6.*"
thiserror = "2.0.12"
